/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.CategorySeries;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.XChartPanel;
import dao.ReportDAO;
import model.NameValue;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Acer
 */
public class ChartsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Charts
     */
    public ChartsPanel() {
        initComponents();
        initXCharts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sellItemCharts = new javax.swing.JPanel();
        dailySalesCharts = new javax.swing.JPanel();
        wasteItemCharts = new javax.swing.JPanel();
        salesByCategoryCharts = new javax.swing.JPanel();
        headerCharts = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 760));
        setMinimumSize(new java.awt.Dimension(1080, 760));
        setPreferredSize(new java.awt.Dimension(1080, 760));

        sellItemCharts.setBackground(new java.awt.Color(255, 255, 255));
        sellItemCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        sellItemCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        sellItemCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        sellItemCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout sellItemChartsLayout = new javax.swing.GroupLayout(sellItemCharts);
        sellItemCharts.setLayout(sellItemChartsLayout);
        sellItemChartsLayout.setHorizontalGroup(
            sellItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        sellItemChartsLayout.setVerticalGroup(
            sellItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        dailySalesCharts.setBackground(new java.awt.Color(255, 255, 255));
        dailySalesCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        dailySalesCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        dailySalesCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        dailySalesCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout dailySalesChartsLayout = new javax.swing.GroupLayout(dailySalesCharts);
        dailySalesCharts.setLayout(dailySalesChartsLayout);
        dailySalesChartsLayout.setHorizontalGroup(
            dailySalesChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        dailySalesChartsLayout.setVerticalGroup(
            dailySalesChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        wasteItemCharts.setBackground(new java.awt.Color(255, 255, 255));
        wasteItemCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        wasteItemCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        wasteItemCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        wasteItemCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout wasteItemChartsLayout = new javax.swing.GroupLayout(wasteItemCharts);
        wasteItemCharts.setLayout(wasteItemChartsLayout);
        wasteItemChartsLayout.setHorizontalGroup(
            wasteItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        wasteItemChartsLayout.setVerticalGroup(
            wasteItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        salesByCategoryCharts.setBackground(new java.awt.Color(255, 255, 255));
        salesByCategoryCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        salesByCategoryCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        salesByCategoryCharts.setMinimumSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout salesByCategoryChartsLayout = new javax.swing.GroupLayout(salesByCategoryCharts);
        salesByCategoryCharts.setLayout(salesByCategoryChartsLayout);
        salesByCategoryChartsLayout.setHorizontalGroup(
            salesByCategoryChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        salesByCategoryChartsLayout.setVerticalGroup(
            salesByCategoryChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        headerCharts.setBackground(new java.awt.Color(255, 255, 255));
        headerCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        headerCharts.setMaximumSize(new java.awt.Dimension(32767, 48));
        headerCharts.setMinimumSize(new java.awt.Dimension(100, 48));
        headerCharts.setPreferredSize(new java.awt.Dimension(100, 48));

        javax.swing.GroupLayout headerChartsLayout = new javax.swing.GroupLayout(headerCharts);
        headerCharts.setLayout(headerChartsLayout);
        headerChartsLayout.setHorizontalGroup(
            headerChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerChartsLayout.setVerticalGroup(
            headerChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerCharts, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sellItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesByCategoryCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wasteItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailySalesCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailySalesCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wasteItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesByCategoryCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initXCharts() {
        sellItemCharts.setLayout(new BorderLayout());
        dailySalesCharts.setLayout(new BorderLayout());
        wasteItemCharts.setLayout(new BorderLayout());
        salesByCategoryCharts.setLayout(new BorderLayout());

        ReportDAO dao = new ReportDAO();

        List<NameValue> sellers = safe(fetch(() -> dao.topSellers(10)));
        CategoryChart barChart = new CategoryChartBuilder().width(519).height(290)
                .title("Top 10 Best-Selling Items").xAxisTitle("Item").yAxisTitle("Qty Sold").build();
        barChart.addSeries("Qty", labels(sellers), values(sellers));
        styleCat(barChart, new Color(0, 102, 204));
        replace(sellItemCharts, new XChartPanel<>(barChart));

        List<NameValue> daily = safe(fetch(() -> dao.dailySales(30)));
        CategoryChart lineChart = new CategoryChartBuilder().width(519).height(290)
                .title("Daily Sales - Last 30 Days").xAxisTitle("Date").yAxisTitle("Revenue").build();
        lineChart.addSeries("Revenue", labels(daily), values(daily));
        lineChart.getStyler().setDefaultSeriesRenderStyle(CategorySeries.CategorySeriesRenderStyle.Line);
        styleCat(lineChart, new Color(0, 102, 204));
        replace(dailySalesCharts, new XChartPanel<>(lineChart));

        List<NameValue> cats = fetch(() -> dao.salesByCategory());
        PieChart pieChart = new PieChartBuilder().width(519).height(290)
                .title("Sales by Category").build();
        if (cats == null || cats.isEmpty()) {
            pieChart.addSeries("(no data)", 1);
        } else {
            for (NameValue nv : cats) pieChart.addSeries(nv.getLabel(), nv.getValue());
        }
        pieChart.getStyler().setChartBackgroundColor(Color.WHITE);
        pieChart.getStyler().setCircular(true);
        replace(salesByCategoryCharts, new XChartPanel<>(pieChart));

        List<NameValue> waste = safe(fetch(() -> dao.topWaste(10)));
        CategoryChart wasteChart = new CategoryChartBuilder().width(519).height(290)
                .title("Top Waste Items (by Cost)").xAxisTitle("Item").yAxisTitle("Waste Cost").build();
        wasteChart.addSeries("Waste", labels(waste), values(waste));
        styleCat(wasteChart, new Color(204, 0, 0));
        replace(wasteItemCharts, new XChartPanel<>(wasteChart));

        this.revalidate();
        this.repaint();
    }

    private interface Fetch { List<NameValue> get(); }

    private List<NameValue> fetch(Fetch f) {
        try { return f.get(); } catch (RuntimeException e) { return new ArrayList<>(); }
    }

    private List<NameValue> safe(List<NameValue> in) {
        if (in == null || in.isEmpty()) {
            List<NameValue> ph = new ArrayList<>();
            ph.add(new NameValue("(no data)", 0));
            return ph;
        }
        return in;
    }

    private List<String> labels(List<NameValue> in) {
        List<String> l = new ArrayList<>();
        for (NameValue nv : in) {
            String s = nv.getLabel() == null ? "" : nv.getLabel();
            if (s.length() > 14) s = s.substring(0, 13) + "...";
            l.add(s);
        }
        return l;
    }

    private List<Number> values(List<NameValue> in) {
        List<Number> l = new ArrayList<>();
        for (NameValue nv : in) l.add(nv.getValue());
        return l;
    }

    private void styleCat(CategoryChart c, Color series) {
        c.getStyler().setChartBackgroundColor(Color.WHITE);
        c.getStyler().setPlotBackgroundColor(new Color(245, 245, 245));
        c.getStyler().setSeriesColors(new Color[]{ series });
        c.getStyler().setLegendVisible(false);
        c.getStyler().setLocale(java.util.Locale.US);
        c.getStyler().setYAxisDecimalPattern("#,##0");
        c.getStyler().setXAxisLabelRotation(45);
    }

    private void replace(javax.swing.JPanel host, java.awt.Component chart) {
        host.removeAll();
        host.add(chart, BorderLayout.CENTER);
        host.revalidate();
        host.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dailySalesCharts;
    private javax.swing.JPanel headerCharts;
    private javax.swing.JPanel salesByCategoryCharts;
    private javax.swing.JPanel sellItemCharts;
    private javax.swing.JPanel wasteItemCharts;
    // End of variables declaration//GEN-END:variables
}
