/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import db.DBConnection;
import util.ComboItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wisdo
 */
public class MasterItemPanel extends javax.swing.JPanel {

    private DefaultTableModel model;
    private int selectedItemId = -1;
    /**
     * Creates new form MasterItem_Panel
     */
    public MasterItemPanel() {
        initComponents();
        loadCategory();
        loadOutlet();
        loadTable();
        tableListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void tableListener() {
        MasterItemTable.getSelectionModel().addListSelectionListener(e -> {
            int row = MasterItemTable.getSelectedRow();

            if (row != -1 && model.getValueAt(row, 0) != null) {
                selectedItemId = Integer.parseInt(model.getValueAt(row, 0).toString());

                txtItemCode.setText(model.getValueAt(row, 1).toString());
                txtDesc.setText(model.getValueAt(row, 2).toString());
                txtItemClass.setSelectedItem(model.getValueAt(row, 3).toString());

                String categoryLabel = model.getValueAt(row, 4).toString();
                for (int i = 0; i < txtCategory.getItemCount(); i++) {
                    ComboItem item = (ComboItem) txtCategory.getItemAt(i);
                    if (item.getLabel().equals(categoryLabel)) {
                        txtCategory.setSelectedIndex(i);
                        break;
                    }
                }

                String outletLabel = model.getValueAt(row, 5).toString();
                for (int i = 0; i < txtOutlet.getItemCount(); i++) {
                    ComboItem item = (ComboItem) txtOutlet.getItemAt(i);
                    if (item.getLabel().equals(outletLabel)) {
                        txtOutlet.setSelectedIndex(i);
                        break;
                    }
                }

                txtBaseUnit.setSelectedItem(model.getValueAt(row, 6).toString());
                txtPurchUnit.setSelectedItem(model.getValueAt(row, 7).toString());
                txtCurrCost.setText(model.getValueAt(row, 8).toString());
                txtSellPrice.setText(model.getValueAt(row, 9).toString());
                txtStatus.setSelectedItem(model.getValueAt(row, 10).toString());
            }
        });
    }
    
    
    private void updateItem(){
        try {

            if (selectedItemId == 0) {

                JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
                return;
            }

            Connection conn = DBConnection.connect();

            ComboItem category = (ComboItem) txtCategory.getSelectedItem();
            ComboItem outlet = (ComboItem) txtOutlet.getSelectedItem();

            String sql =
                "UPDATE master_item SET " +
                "item_code=?, " +
                "description=?, " +
                "item_class=?, " +
                "category_id=?, " +
                "outlet_id=?, " +
                "base_unit=?, " +
                "purchase_unit=?, " +
                "current_cost=?, " +
                "selling_price=?, " +
                "status=? " +
                "WHERE item_id=?";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, txtItemCode.getText());
            ps.setString(2, txtDesc.getText());
            ps.setString(3, txtItemClass.getSelectedItem().toString());

            ps.setInt(4, category.getValue());
            ps.setInt(5, outlet.getValue());

            ps.setString(6, txtBaseUnit.getSelectedItem().toString());
            ps.setString(7, txtPurchUnit.getSelectedItem().toString());

            ps.setDouble(8, Double.parseDouble(txtCurrCost.getText()));
            ps.setDouble(9, Double.parseDouble(txtSellPrice.getText()));

            ps.setString(10, txtStatus.getSelectedItem().toString());

            ps.setInt(11, selectedItemId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate");

            loadTable();
            clearForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void deleteItem(){
        try {

            if (selectedItemId == 0) {

                JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(
                null,
                "Yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {

                Connection conn = DBConnection.connect();

                String sql = "DELETE FROM master_item WHERE item_id=?";

                PreparedStatement ps = conn.prepareStatement(sql);

                ps.setInt(1, selectedItemId);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

                loadTable();
                clearForm();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void addItem(){
        try {

                Connection conn = DBConnection.connect();

                ComboItem category = (ComboItem) txtCategory.getSelectedItem();
                ComboItem outlet = (ComboItem) txtOutlet.getSelectedItem();

                String sql =
                    "INSERT INTO master_item " +
                    "(item_code, description, item_class, category_id, outlet_id, " +
                    "base_unit, purchase_unit, qty_per_purchase_unit, " +
                    "current_cost, selling_price, status) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement ps = conn.prepareStatement(sql);

                ps.setString(1, txtItemCode.getText());
                ps.setString(2, txtDesc.getText());
                ps.setString(3, txtItemClass.getSelectedItem().toString());

                ps.setInt(4, category.getValue());
                ps.setInt(5, outlet.getValue());

                ps.setString(6, txtBaseUnit.getSelectedItem().toString());
                ps.setString(7, txtPurchUnit.getSelectedItem().toString());

                ps.setDouble(8, 1);

                ps.setDouble(9, Double.parseDouble(txtCurrCost.getText()));
                ps.setDouble(10, Double.parseDouble(txtSellPrice.getText()));

                ps.setString(11, txtStatus.getSelectedItem().toString());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");

                loadTable();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void clearForm() {

        txtItemCode.setText("");
        txtDesc.setText("");

        txtCurrCost.setText("");
        txtSellPrice.setText("");

        txtItemClass.setSelectedIndex(0);
        txtCategory.setSelectedIndex(0);
        txtOutlet.setSelectedIndex(0);

        txtBaseUnit.setSelectedIndex(0);
        txtPurchUnit.setSelectedIndex(0);

        txtStatus.setSelectedIndex(0);

        MasterItemTable.clearSelection();

        selectedItemId = 0;
    }

    private void searchData() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Item Code");
        model.addColumn("Description");
        model.addColumn("Item Class");
        model.addColumn("Category");
        model.addColumn("Outlet");
        model.addColumn("Base Unit");
        model.addColumn("Cost");
        model.addColumn("Price");
        model.addColumn("Status");

        try {

            Connection conn = DBConnection.connect();

            String sql =
                "SELECT " +
                "mi.item_id, " +
                "mi.item_code, " +
                "mi.description, " +
                "mi.item_class, " +
                "c.category_name, " +
                "o.outlet_code, " +
                "mi.base_unit, " +
                "mi.current_cost, " +
                "mi.selling_price, " +
                "mi.status " +
                "FROM master_item mi " +
                "LEFT JOIN category c ON mi.category_id = c.category_id " +
                "LEFT JOIN outlet o ON mi.outlet_id = o.outlet_id " +
                "WHERE mi.item_code LIKE ? " +
                "OR mi.description LIKE ? " +
                "ORDER BY mi.item_id DESC";

            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, "%" + txtSearch.getText() + "%");
            ps.setString(2, "%" + txtSearch.getText() + "%");

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                model.addRow(new Object[] {
                    rs.getInt("item_id"),
                    rs.getString("item_code"),
                    rs.getString("description"),
                    rs.getString("item_class"),
                    rs.getString("category_name"),
                    rs.getString("outlet_code"),
                    rs.getString("base_unit"),
                    rs.getDouble("current_cost"),
                    rs.getDouble("selling_price"),
                    rs.getString("status")
                });
            }

            MasterItemTable.setModel(model);
            MasterItemTable.getColumnModel().getColumn(0).setMinWidth(0);
            MasterItemTable.getColumnModel().getColumn(0).setMaxWidth(0);
            MasterItemTable.getColumnModel().getColumn(0).setWidth(0);

            MasterItemTable.getColumnModel().getColumn(0).setMinWidth(0);
            MasterItemTable.getColumnModel().getColumn(0).setMaxWidth(0);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void loadCategory() {

        txtCategory.removeAllItems();

        try {
            Connection conn = DBConnection.connect();

            String sql = "SELECT category_id, category_name FROM category ORDER BY category_name";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                txtCategory.addItem(
                    new ComboItem(
                        rs.getInt("category_id"),
                        rs.getString("category_name")
                    )
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void loadOutlet() {

        txtOutlet.removeAllItems();

        try {
            Connection conn = DBConnection.connect();

            String sql = "SELECT outlet_id, outlet_code FROM outlet ORDER BY outlet_code";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                txtOutlet.addItem(
                    new ComboItem(
                        rs.getInt("outlet_id"),
                        rs.getString("outlet_code")
                    )
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void loadTable() {

        model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Item Code");
        model.addColumn("Description");
        model.addColumn("Item Class");
        model.addColumn("Category");
        model.addColumn("Outlet");
        model.addColumn("Base Unit");
        model.addColumn("Cost");
        model.addColumn("Price");
        model.addColumn("Status");

        try {

            Connection conn = DBConnection.connect();

            String sql =
                "SELECT " +
                "mi.item_id, " +
                "mi.item_code, " +
                "mi.description, " +
                "mi.item_class, " +
                "c.category_name, " +
                "o.outlet_code, " +
                "mi.base_unit, " +
                "mi.current_cost, " +
                "mi.selling_price, " +
                "mi.status " +
                "FROM master_item mi " +
                "LEFT JOIN category c ON mi.category_id = c.category_id " +
                "LEFT JOIN outlet o ON mi.outlet_id = o.outlet_id " +
                "ORDER BY mi.item_id DESC";

            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                model.addRow(new Object[] {
                    rs.getInt("item_id"),
                    rs.getString("item_code"),
                    rs.getString("description"),
                    rs.getString("item_class"),
                    rs.getString("category_name"),
                    rs.getString("outlet_code"),
                    rs.getString("base_unit"),
                    rs.getDouble("current_cost"),
                    rs.getDouble("selling_price"),
                    rs.getString("status")
                });
            }

            MasterItemTable.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemClass = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtOutlet = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtBaseUnit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPurchUnit = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtCurrCost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSellPrice = new javax.swing.JTextField();
        txtStatus = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MasterItemTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Items — Manage Items");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Item Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(938, 938, 938))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel4.setText("Item Code:");

        txtItemCode.addActionListener(this::txtItemCodeActionPerformed);

        txtDesc.addActionListener(this::txtDescActionPerformed);

        jLabel14.setText("Description:");

        jLabel5.setText("Item Class:");

        txtItemClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALKOHOL", "ASSET", "ATK", "EQUIPMENT", "CHEMICAL", "CK", "DESSERT", "DRY GOODS", "IKAN OLAHAN", "DRY CHINA", "GARNISH", "SAYUR", "NONALKOHOL", "PACKAGING", "UTENSIL", "SAKE WINE", "SOFTDRINK", "SUPPLIES", "UNIFORM", "UTN IMP" }));

        jLabel7.setText("Category:");

        jLabel8.setText("outlet");

        jLabel12.setText("Base Unit:");

        txtBaseUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ml", "Botol", "Gram", "Kaleng", "Unit", "Pcs", "Lot", "Set", "Meter", "Pak", "Roll", "Buku", "Dus", "Rim", "Box", "Lembar", "Jrigen", "Can", "Slice", "Ekor", "Pail", "Butir", "Kg", "Jar", "Galon", "Pot", "Pasang", "Potong", "Liter", "Sisir", "Tabung" }));
        txtBaseUnit.addActionListener(this::txtBaseUnitActionPerformed);

        jLabel9.setText("purchase Unit:");

        txtPurchUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Botol", "Barel", "Kaleng", "Can", "Pak", "Unit", "Pcs", "Lot", "Set", "Meter", "Roll", "Buku", "Dus", "Box", "Rim", "Lembar", "Jrigen", "Kg", "Gram", "Ml", "Slice", "Ekor", "Pail", "Carton", "Galon", "Toples", "Bal", "Butir", "Jar", "Ctn", "Karton", "Jerigen", "Jrg", "Pak 2 Kg", "Pot", "Pasang", "Potong", "Liter", "Sisir", "Tabung" }));

        jLabel10.setText("Curennt Cost: ");

        jLabel11.setText("Selling Price :");

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        txtStatus.addActionListener(this::txtStatusActionPerformed);

        jLabel13.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12)
                        .addGap(44, 44, 44)
                        .addComponent(txtBaseUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtItemClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOutlet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(36, 36, 36)
                                .addComponent(txtPurchUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel13)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurrCost)
                                    .addComponent(txtSellPrice)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtBaseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPurchUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtItemClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtCurrCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnAdd.setBackground(new java.awt.Color(0, 102, 204));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+ Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        jLabel2.setText("Search:");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(232, 232, 232)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnRefresh)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        MasterItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(MasterItemTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addItem();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtBaseUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseUnitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateItem();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteItem();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MasterItemTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> txtBaseUnit;
    private javax.swing.JComboBox<ComboItem> txtCategory;
    private javax.swing.JTextField txtCurrCost;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JComboBox<String> txtItemClass;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JComboBox<ComboItem> txtOutlet;
    private javax.swing.JComboBox<String> txtPurchUnit;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
