/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Theresa
 */
public class OutletsPanel extends javax.swing.JPanel {

    private DefaultTableModel model;
    private int selectedOutletId = -1;
    /**
     * Creates new form OutletsPanel
     */
    public OutletsPanel() {
        initComponents();
model = (DefaultTableModel) OutletTable.getModel();

        loadData();
        tableListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void clearForm() {

        txtOutletCode.setText("");
        txtOutletName.setText("");
        txtStatus.setSelectedIndex(0);

        selectedOutletId = -1;

        OutletTable.clearSelection();
    }
    
    private void searchData() {

        model.setRowCount(0);

        String keyword = txtSearch.getText().trim();

        String sql = """
                     SELECT 
                        o.outlet_id,
                        o.outlet_code,
                        o.outlet_name,
                        COUNT(mi.item_id) AS item_count,
                        o.status
                     FROM outlet o
                     LEFT JOIN master_item mi
                        ON mi.outlet_id = o.outlet_id
                     WHERE o.outlet_code LIKE ?
                        OR o.outlet_name LIKE ?
                        OR o.status LIKE ?
                     GROUP BY o.outlet_id
                     """;

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("outlet_code"),
                    rs.getString("outlet_name"),
                    rs.getInt("item_count"),
                    rs.getString("status")
                });
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Search gagal: " + e.getMessage());
        }
    }
    
    private void loadData() {

        model.setRowCount(0);

        String sql = """
                     SELECT 
                        o.outlet_id,
                        o.outlet_code,
                        o.outlet_name,
                        COUNT(mi.item_id) AS item_count,
                        o.status
                     FROM outlet o
                     LEFT JOIN master_item mi
                        ON mi.outlet_id = o.outlet_id
                     GROUP BY o.outlet_id
                     ORDER BY o.outlet_id ASC
                     """;

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()
        ) {

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("outlet_code"),
                    rs.getString("outlet_name"),
                    rs.getInt("item_count"),
                    rs.getString("status")
                });
            }

            jLabel7.setText(
                    "Showing " + model.getRowCount() + " outlets"
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Gagal load data: " + e.getMessage());
        }
    }
    
    private void addOutlet() {

        String code = txtOutletCode.getText().trim().toUpperCase();
        String name = txtOutletName.getText().trim();
        String status = txtStatus.getSelectedItem().toString();

        if (code.isEmpty() || name.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi!");
            return;
        }

        String sql = """
                     INSERT INTO outlet
                     (outlet_code, outlet_name, status)
                     VALUES (?, ?, ?)
                     """;

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(1, code);
            ps.setString(2, name);
            ps.setString(3, status);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Data berhasil ditambahkan");

            loadData();
            clearForm();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Gagal tambah data: " + e.getMessage());
        }
    }

    private void tableListener() {

        OutletTable.getSelectionModel().addListSelectionListener(e -> {

            int row = OutletTable.getSelectedRow();

            if (row != -1) {

                String code = model.getValueAt(row, 0).toString();

                txtOutletCode.setText(code);

                txtOutletName.setText(
                        model.getValueAt(row, 1).toString()
                );

                txtStatus.setSelectedItem(
                        model.getValueAt(row, 3).toString()
                );

                getSelectedOutletId(code);
            }
        });
    }

    private void getSelectedOutletId(String code) {

        String sql = """
                     SELECT outlet_id
                     FROM outlet
                     WHERE outlet_code = ?
                     """;

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(1, code);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                selectedOutletId = rs.getInt("outlet_id");
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Gagal ambil ID: " + e.getMessage());
        }
    }
    
    private void updateOutlet() {

        if (selectedOutletId == -1) {

            JOptionPane.showMessageDialog(this,
                    "Pilih data terlebih dahulu!");
            return;
        }

        String sql = """
                     UPDATE outlet
                     SET outlet_code = ?,
                         outlet_name = ?,
                         status = ?
                     WHERE outlet_id = ?
                     """;

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(1,
                    txtOutletCode.getText().trim().toUpperCase());

            ps.setString(2,
                    txtOutletName.getText().trim());

            ps.setString(3,
                    txtStatus.getSelectedItem().toString());

            ps.setInt(4, selectedOutletId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Data berhasil diupdate");

            loadData();
            clearForm();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Gagal update: " + e.getMessage());
        }
    }
    
    private void deleteOutlet() {

        if (selectedOutletId == -1) {

            JOptionPane.showMessageDialog(this,
                    "Pilih data terlebih dahulu!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM outlet WHERE outlet_id = ?";

        try (
            Connection conn = DBConnection.connect();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setInt(1, selectedOutletId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus");

            loadData();
            clearForm();

        } catch (SQLException e) {

            String msg = e.getMessage() == null ? "" : e.getMessage();
            if (msg.toLowerCase().contains("foreign key")) {
                String currentStatus = txtStatus.getSelectedItem() == null
                        ? "" : txtStatus.getSelectedItem().toString();
                if ("Inactive".equalsIgnoreCase(currentStatus)) {
                    JOptionPane.showMessageDialog(this,
                            "Outlet ini masih dipakai di transaksi lain, tidak bisa dihapus.\n"
                          + "Tapi statusnya sudah Inactive, jadi tidak muncul lagi di form transaksi.",
                            "Tidak bisa dihapus", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                int change = JOptionPane.showConfirmDialog(this,
                        "Outlet ini masih dipakai di transaksi lain, tidak bisa dihapus.\n"
                      + "Set Status ke Inactive saja?",
                        "Tidak bisa dihapus", JOptionPane.YES_NO_OPTION);
                if (change == JOptionPane.YES_OPTION) {
                    try (Connection c2 = DBConnection.connect();
                         PreparedStatement p2 = c2.prepareStatement(
                                 "UPDATE outlet SET status='Inactive' WHERE outlet_id=?")) {
                        p2.setInt(1, selectedOutletId);
                        p2.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Status diubah ke Inactive.");
                        loadData();
                        clearForm();
                    } catch (SQLException ex2) {
                        JOptionPane.showMessageDialog(this, "Gagal: " + ex2.getMessage());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Gagal hapus: " + e.getMessage());
            }
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOutletCode = new javax.swing.JTextField();
        txtStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtOutletName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutletTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Outlets - Manage Outlet Locations");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(0, 102, 204));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+ Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        jLabel5.setText("Search:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnRefresh)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 192, 192)));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 192, 192)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Outlet Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Outlet Code:");

        jLabel4.setText("Status:");

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel6.setText("Outlet Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStatus, 0, 359, Short.MAX_VALUE)
                    .addComponent(txtOutletCode))
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOutletName, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOutletCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtOutletName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        OutletTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Outlet Code", "Outlet Name", "Item Count", "Status"
            }
        ));
        OutletTable.setGridColor(new java.awt.Color(204, 204, 204));
        OutletTable.setShowHorizontalLines(true);
        OutletTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(OutletTable);

        jLabel7.setText("Showing 9 of 9 outlets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addOutlet();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateOutlet();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        // TODO add your handling code here:
        deleteOutlet();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
       loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OutletTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtOutletCode;
    private javax.swing.JTextField txtOutletName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
