/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

/**
 *
 * @author dayen
 */
public class CategoryItemForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoryItemForm.class.getName());

    /**
     * Creates new form CategoryItemForm
     */
    public CategoryItemForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCentralKitchen = new javax.swing.JTextField();
        btnDelete = new java.awt.Button();
        btnReset = new java.awt.Button();
        btnAdd = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategory = new javax.swing.JTable();
        scrollbar1 = new java.awt.Scrollbar();
        btnUpdate = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category Item Form");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Category Name");

        txtCentralKitchen.addActionListener(this::txtCentralKitchenActionPerformed);

        btnDelete.setLabel("Delete Item");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnReset.setLabel("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnAdd.setLabel("Add Item");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        jTableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCategory);

        btnUpdate.setActionCommand("Update Item");
        btnUpdate.setLabel("Update Item");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCentralKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCentralKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(scrollbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(277, 277, 277))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCentralKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCentralKitchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCentralKitchenActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String key = txtItemNumber.getText().trim();
        if (key.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih baris atau isi Item Number dulu");
            return;
        }
        int ok = JOptionPane.showConfirmDialog(this, "Hapus item " + key + " ?",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (ok != JOptionPane.YES_OPTION) return;
        String sql = "DELETE FROM item WHERE item_number=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, key);
            int n = ps.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                kosong();
                datatable();
            } else {
                JOptionPane.showMessageDialog(this, "Item tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kosong();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtItemNumber.getText().trim().isEmpty() || txtItemDesc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Item Number dan Description wajib diisi");
            return;
        }
        String sql = "INSERT INTO item (item_number, item_description, item_class, uom_schedule, "
        + "base_uom, purchasing_uom, standard_cost, current_cost, qty_purchase_uom, "
        + "price_list, status, user_classification, item_category, outlet_name) "
        + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, txtItemNumber.getText().trim());
            ps.setString(2, txtItemDesc.getText().trim());
            ps.setString(3, String.valueOf(jComboBoxItemClass.getSelectedItem()));
            ps.setString(4, txtSchUoM.getText().trim());
            ps.setString(5, txtBaseUoM.getText().trim());
            ps.setString(6, txtPurchUoM.getText().trim());
            ps.setDouble(7, parseNum(txtStandardCost.getText()));
            ps.setDouble(8, parseNum(txtCurrCost.getText()));
            ps.setDouble(9, parseNum(txtQtyUoM.getText()));
            ps.setDouble(10, parseNum(txtPriceList.getText()));
            ps.setString(11, "YES".equalsIgnoreCase(String.valueOf(jComboBoxStatus.getSelectedItem())) ? "Yes" : "No");
            ps.setString(12, String.valueOf(jComboBoxClassification.getSelectedItem()));
            ps.setString(13, String.valueOf(jComboBoxCategory.getSelectedItem()));
            ps.setString(14, String.valueOf(jComboBoxOutletName.getSelectedItem()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            kosong();
            datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String key = txtItemNumber.getText().trim();
        if (key.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih baris dulu untuk update");
            return;
        }
        String sql = "UPDATE item SET item_description=?, item_class=?, uom_schedule=?, "
        + "base_uom=?, purchasing_uom=?, standard_cost=?, current_cost=?, "
        + "qty_purchase_uom=?, price_list=?, status=?, user_classification=?, "
        + "item_category=?, outlet_name=? "
        + "WHERE item_number=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, txtItemDesc.getText().trim());
            ps.setString(2, String.valueOf(jComboBoxItemClass.getSelectedItem()));
            ps.setString(3, txtSchUoM.getText().trim());
            ps.setString(4, txtBaseUoM.getText().trim());
            ps.setString(5, txtPurchUoM.getText().trim());
            ps.setDouble(6, parseNum(txtStandardCost.getText()));
            ps.setDouble(7, parseNum(txtCurrCost.getText()));
            ps.setDouble(8, parseNum(txtQtyUoM.getText()));
            ps.setDouble(9, parseNum(txtPriceList.getText()));
            ps.setString(10, "YES".equalsIgnoreCase(String.valueOf(jComboBoxStatus.getSelectedItem())) ? "Yes" : "No");
            ps.setString(11, String.valueOf(jComboBoxClassification.getSelectedItem()));
            ps.setString(12, String.valueOf(jComboBoxCategory.getSelectedItem()));
            ps.setString(13, String.valueOf(jComboBoxOutletName.getSelectedItem()));
            ps.setString(14, key);
            int n = ps.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                kosong();
                datatable();
            } else {
                JOptionPane.showMessageDialog(this, "Item tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal diubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoryItemForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdd;
    private java.awt.Button btnDelete;
    private java.awt.Button btnReset;
    private java.awt.Button btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategory;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JTextField txtCentralKitchen;
    // End of variables declaration//GEN-END:variables
}
