/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package tampilan;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Arrays;
/**
 *
 * @author Acer
 */
public class ChartsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Charts
     */
    public ChartsPanel() {
        initComponents();
        initXCharts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sellItemCharts = new javax.swing.JPanel();
        dailySalesCharts = new javax.swing.JPanel();
        wasteItemCharts = new javax.swing.JPanel();
        salesByCategoryCharts = new javax.swing.JPanel();
        headerCharts = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 760));
        setMinimumSize(new java.awt.Dimension(1080, 760));
        setPreferredSize(new java.awt.Dimension(1080, 760));

        sellItemCharts.setBackground(new java.awt.Color(255, 255, 255));
        sellItemCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        sellItemCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        sellItemCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        sellItemCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout sellItemChartsLayout = new javax.swing.GroupLayout(sellItemCharts);
        sellItemCharts.setLayout(sellItemChartsLayout);
        sellItemChartsLayout.setHorizontalGroup(
            sellItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        sellItemChartsLayout.setVerticalGroup(
            sellItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        dailySalesCharts.setBackground(new java.awt.Color(255, 255, 255));
        dailySalesCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        dailySalesCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        dailySalesCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        dailySalesCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout dailySalesChartsLayout = new javax.swing.GroupLayout(dailySalesCharts);
        dailySalesCharts.setLayout(dailySalesChartsLayout);
        dailySalesChartsLayout.setHorizontalGroup(
            dailySalesChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        dailySalesChartsLayout.setVerticalGroup(
            dailySalesChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        wasteItemCharts.setBackground(new java.awt.Color(255, 255, 255));
        wasteItemCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        wasteItemCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        wasteItemCharts.setMinimumSize(new java.awt.Dimension(519, 290));
        wasteItemCharts.setPreferredSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout wasteItemChartsLayout = new javax.swing.GroupLayout(wasteItemCharts);
        wasteItemCharts.setLayout(wasteItemChartsLayout);
        wasteItemChartsLayout.setHorizontalGroup(
            wasteItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        wasteItemChartsLayout.setVerticalGroup(
            wasteItemChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        salesByCategoryCharts.setBackground(new java.awt.Color(255, 255, 255));
        salesByCategoryCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        salesByCategoryCharts.setMaximumSize(new java.awt.Dimension(519, 290));
        salesByCategoryCharts.setMinimumSize(new java.awt.Dimension(519, 290));

        javax.swing.GroupLayout salesByCategoryChartsLayout = new javax.swing.GroupLayout(salesByCategoryCharts);
        salesByCategoryCharts.setLayout(salesByCategoryChartsLayout);
        salesByCategoryChartsLayout.setHorizontalGroup(
            salesByCategoryChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        salesByCategoryChartsLayout.setVerticalGroup(
            salesByCategoryChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        headerCharts.setBackground(new java.awt.Color(255, 255, 255));
        headerCharts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        headerCharts.setMaximumSize(new java.awt.Dimension(32767, 48));
        headerCharts.setMinimumSize(new java.awt.Dimension(100, 48));
        headerCharts.setPreferredSize(new java.awt.Dimension(100, 48));

        javax.swing.GroupLayout headerChartsLayout = new javax.swing.GroupLayout(headerCharts);
        headerCharts.setLayout(headerChartsLayout);
        headerChartsLayout.setHorizontalGroup(
            headerChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerChartsLayout.setVerticalGroup(
            headerChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerCharts, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sellItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesByCategoryCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wasteItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dailySalesCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailySalesCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wasteItemCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesByCategoryCharts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void initXCharts() {
        // 1. Set Layout penampung ke BorderLayout supaya grafik otomatis memenuhi ukuran panel
        sellItemCharts.setLayout(new BorderLayout());
        dailySalesCharts.setLayout(new BorderLayout());
        wasteItemCharts.setLayout(new BorderLayout());
        salesByCategoryCharts.setLayout(new BorderLayout());

        // ------------------------------------------
        // CHART 1: Top 5 Selling Items (Bar Chart) -> sellItemCharts
        // ------------------------------------------
        CategoryChart barChart = new CategoryChartBuilder()
                .width(519).height(290).title("Top 5 Selling Items")
                .xAxisTitle("Nama Barang").yAxisTitle("Jumlah Terjual (Pcs)").build();

        barChart.addSeries("Terjual", 
                Arrays.asList("Kopi Susu", "Roti Bakar", "Indomie Goreng", "Es Teh Manis", "Kentang Goreng"), 
                Arrays.asList(142, 98, 85, 74, 52));
        
        barChart.getStyler().setChartBackgroundColor(Color.WHITE);
        barChart.getStyler().setPlotBackgroundColor(new Color(245, 245, 245));
        barChart.getStyler().setLegendVisible(false);
        barChart.getStyler().setToolTipsEnabled(true);

        XChartPanel<CategoryChart> panelSellItem = new XChartPanel<>(barChart);
        sellItemCharts.add(panelSellItem, BorderLayout.CENTER);


        // ------------------------------------------
        // CHART 2: Daily Sales Trend (Line Chart) -> dailySalesCharts
        // ------------------------------------------
        XYChart lineChart = new XYChartBuilder()
                .width(519).height(290).title("Tren Penjualan Minggu Ini")
                .xAxisTitle("Hari").yAxisTitle("Omset (Rupiah)").build();

        lineChart.addSeries("Pendapatan", 
                Arrays.asList(1, 2, 3, 4, 5, 6, 7), 
                Arrays.asList(1200, 1500, 1300, 1700, 2100, 3200, 2800));
        
        lineChart.getStyler().setChartBackgroundColor(Color.WHITE);
        lineChart.getStyler().setPlotBackgroundColor(new Color(245, 245, 245));
        lineChart.getStyler().setLegendPosition(org.knowm.xchart.style.Styler.LegendPosition.InsideNW);
        lineChart.getStyler().setMarkerSize(8);

        XChartPanel<XYChart> panelDailySales = new XChartPanel<>(lineChart);
        dailySalesCharts.add(panelDailySales, BorderLayout.CENTER);


        // ------------------------------------------
        // CHART 3: Sales by Category (Pie Chart) -> salesByCategoryCharts
        // ------------------------------------------
        PieChart pieChart = new PieChartBuilder()
                .width(519).height(290).title("Persentase Penjualan per Kategori").build();

        pieChart.addSeries("Makanan Berat", 40);
        pieChart.addSeries("Minuman Coffee", 25);
        pieChart.addSeries("Cemilan / Snacks", 20);
        pieChart.addSeries("Minuman Non-Coffee", 15);
        
        pieChart.getStyler().setChartBackgroundColor(Color.WHITE);
        pieChart.getStyler().setLegendPosition(org.knowm.xchart.style.Styler.LegendPosition.InsideNE);
        pieChart.getStyler().setCircular(true);

        XChartPanel<PieChart> panelCategory = new XChartPanel<>(pieChart);
        salesByCategoryCharts.add(panelCategory, BorderLayout.CENTER);


        // ------------------------------------------
        // CHART 4: Waste Items Tracking (Bar Chart Red) -> wasteItemCharts
        // ------------------------------------------
        CategoryChart wasteChart = new CategoryChartBuilder()
                .width(519).height(290).title("Daftar Produk Terbuang (Waste)")
                .xAxisTitle("Alasan").yAxisTitle("Jumlah Insiden").build();

        wasteChart.addSeries("Kuantitas", 
                Arrays.asList("Bahan Kadaluarsa", "Salah Masak", "Bahan Rusak", "Diskon Karyawan"), 
                Arrays.asList(18, 7, 12, 5));
        
        wasteChart.getStyler().setChartBackgroundColor(Color.WHITE);
        wasteChart.getStyler().setPlotBackgroundColor(new Color(245, 245, 245));
        wasteChart.getStyler().setSeriesColors(new Color[]{new Color(230, 76, 60)}); // Warna merah soft
        wasteChart.getStyler().setLegendVisible(false);
        wasteChart.getStyler().setToolTipsEnabled(true);

        XChartPanel<CategoryChart> panelWaste = new XChartPanel<>(wasteChart);
        wasteItemCharts.add(panelWaste, BorderLayout.CENTER);

        // 2. Paksa Swing merender ulang tampilan komponen agar grafik langsung muncul
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dailySalesCharts;
    private javax.swing.JPanel headerCharts;
    private javax.swing.JPanel salesByCategoryCharts;
    private javax.swing.JPanel sellItemCharts;
    private javax.swing.JPanel wasteItemCharts;
    // End of variables declaration//GEN-END:variables
}
