/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;
import helper.ComboItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import org.mindrot.jbcrypt.BCrypt;
/**
 *
 * @author Theresa
 */
public class UsersPanel extends javax.swing.JPanel {

    private DefaultTableModel model;
    private int selectedUserId = -1;
    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
        
        model = new DefaultTableModel(
        new String[]{
            "ID",
            "Username",
            "Role",
            "Outlet",
            "Created",
            "Last Login",
            "Status"
        }, 0
    );

    tableUser.setModel(model);
    tableUser.getColumnModel().getColumn(0).setMinWidth(0);
    tableUser.getColumnModel().getColumn(0).setMaxWidth(0);
    tableUser.getColumnModel().getColumn(0).setWidth(0);
    
        loadOutlets();
        loadData();
        tableListener();
    }

    private void tableListener(){

        tableUser.getSelectionModel().addListSelectionListener(e -> {

            int row = tableUser.getSelectedRow();

            if (row != -1 && model.getValueAt(row, 0) != null) {

                selectedUserId = Integer.parseInt(
                        model.getValueAt(row, 0).toString()
                );

                txtUsername.setText(
                        model.getValueAt(row, 1).toString()
                );

                txtRole.setSelectedItem(
                        model.getValueAt(row, 2).toString()
                );

                String outletCode =
                        model.getValueAt(row, 3).toString();

                for (int i = 0; i < txtOutlets.getItemCount(); i++) {

                    ComboItem item = txtOutlets.getItemAt(i);

                    if (item.getLabel().equals(outletCode)) {

                        txtOutlets.setSelectedIndex(i);

                        break;
                    }
                }

                txtStatus.setSelectedItem(
                        model.getValueAt(row, 6).toString()
                );
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void searchData() {

       model.setRowCount(0);

       String keyword = txtSearch.getText().trim();

       String sql = """
                    SELECT
                       u.user_id,
                       u.username,
                       u.role,
                       o.outlet_code,
                       u.created_at,
                       u.last_login_at,
                       u.status
                    FROM user u
                    JOIN outlet o
                       ON u.outlet_id = o.outlet_id
                    WHERE
                       u.username LIKE ?
                       OR u.role LIKE ?
                       OR o.outlet_code LIKE ?
                    ORDER BY u.username
                    """;

       try (

               Connection conn = Koneksi.connect();
               PreparedStatement ps = conn.prepareStatement(sql);

               ) {

           ps.setString(1, "%" + keyword + "%");
           ps.setString(2, "%" + keyword + "%");
           ps.setString(3, "%" + keyword + "%");

           ResultSet rs = ps.executeQuery();

           while (rs.next()) {

               model.addRow(new Object[]{
                   rs.getInt("user_id"),
                   rs.getString("username"),
                   rs.getString("role"),
                   rs.getString("outlet_code"),
                   rs.getDate("created_at"),
                   rs.getTimestamp("last_login_at"),
                   rs.getString("status")
               });
           }

       } catch (SQLException e) {

           JOptionPane.showMessageDialog(this,
                   "Search gagal : " + e.getMessage());
       }
   }
    
    private void loadOutlets() {
        try {

        Connection conn = Koneksi.connect();

        String sql = """
                     SELECT
                        outlet_id,
                        outlet_code
                     FROM outlet
                     ORDER BY outlet_code
                     """;

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        txtOutlets.removeAllItems();

        while (rs.next()) {

            txtOutlets.addItem(new ComboItem(
                    rs.getInt("outlet_id"),
                    rs.getString("outlet_code")
                )

            );

        }

    } catch (SQLException e) {

        System.out.println(
                "Error load outlet: " + e.getMessage()
        );
    }

   }
    
    private void loadData() {

        model.setRowCount(0);

        String sql = """
                     SELECT
                        u.user_id,
                        u.username,
                        u.role,
                        o.outlet_code,
                        u.created_at,
                        u.last_login_at,
                        u.status
                     FROM user u
                     JOIN outlet o
                        ON u.outlet_id = o.outlet_id
                     ORDER BY u.username
                     """;

        try (

                Connection conn = Koneksi.connect();
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                ) {

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("user_id"),
                    rs.getString("username"),
                    rs.getString("role"),
                    rs.getString("outlet_code"),
                    rs.getDate("created_at"),
                    rs.getTimestamp("last_login_at"),
                    rs.getString("status")
                });
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Load data gagal : " + e.getMessage());
        }
    }
    
    private void clearForm() {

        txtUsername.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");

        txtRole.setSelectedIndex(0);
        txtOutlets.setSelectedIndex(0);
        txtStatus.setSelectedIndex(0);

        selectedUserId = -1;

        tableUser.clearSelection();
    }
    
    private void addUser(){

        String username = txtUsername.getText().trim();

        String password = new String(txtPassword.getPassword());

        String confirmPassword = new String(
                txtConfirmPassword.getPassword()
        );

        String role = txtRole.getSelectedItem().toString();

        ComboItem selectedOutlet =
                (ComboItem) txtOutlets.getSelectedItem();

        int outletId = selectedOutlet.getValue();

        String status = txtStatus.getSelectedItem().toString();

        if (username.isEmpty()
                || password.isEmpty()
                || confirmPassword.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi");

            return;
        }

        if (!password.equals(confirmPassword)) {

            JOptionPane.showMessageDialog(this,
                    "Confirm password tidak sama");

            return;
        }

        String sql = """
                     INSERT INTO user
                     (
                        username,
                        password_hash,
                        role,
                        outlet_id,
                        status
                     )
                     VALUES (?, ?, ?, ?, ?)
                     """;

        try (

                Connection conn = Koneksi.connect();
                PreparedStatement ps = conn.prepareStatement(sql);

                ) {

            String hashedPassword =
                    BCrypt.hashpw(password, BCrypt.gensalt());

            ps.setString(1, username);
            ps.setString(2, hashedPassword);
            ps.setString(3, role);
            ps.setInt(4, outletId);
            ps.setString(5, status);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "User berhasil ditambahkan");

            clearForm();
            loadData();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Tambah user gagal : " + e.getMessage());
        }
}

    private void updateUser(){

        if (selectedUserId == -1) {

            JOptionPane.showMessageDialog(this,
                    "Pilih data terlebih dahulu");

            return;
        }

        ComboItem selectedOutlet =
                (ComboItem) txtOutlets.getSelectedItem();

        int outletId = selectedOutlet.getValue();

        String sql = """
                     UPDATE user
                     SET
                        username = ?,
                        role = ?,
                        outlet_id = ?,
                        status = ?
                     WHERE user_id = ?
                     """;

        try (

                Connection conn = Koneksi.connect();
                PreparedStatement ps = conn.prepareStatement(sql);

                ) {

            ps.setString(1, txtUsername.getText());
            ps.setString(2, txtRole.getSelectedItem().toString());
            ps.setInt(3, outletId);
            ps.setString(4, txtStatus.getSelectedItem().toString());
            ps.setInt(5, selectedUserId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "User berhasil diupdate");

            clearForm();
            loadData();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Update gagal : " + e.getMessage());
        }
    }
    
    private void deleteUser(){
        if (selectedUserId == -1) {

            JOptionPane.showMessageDialog(this,
                    "Pilih data terlebih dahulu");

            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus user?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM user WHERE user_id = ?";

        try (

                Connection conn = Koneksi.connect();
                PreparedStatement ps = conn.prepareStatement(sql);

                ) {

            ps.setInt(1, selectedUserId);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "User berhasil dihapus");

            clearForm();
            loadData();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Delete gagal : " + e.getMessage());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRole = new javax.swing.JComboBox<>();
        txtOutlets = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Users - Manage Aplication User");

        btnAdd.setBackground(new java.awt.Color(0, 0, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+ Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("User Details");

        jLabel3.setText("Username :");

        jLabel4.setText("Password :");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        jLabel6.setText("Search :");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        jLabel7.setText("Role :");

        jLabel8.setText("Outlet :");

        jLabel9.setText("Status :");

        txtRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Manager", "Staff" }));
        txtRole.addActionListener(this::txtRoleActionPerformed);

        txtOutlets.addActionListener(this::txtOutletsActionPerformed);

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        txtStatus.addActionListener(this::txtStatusActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Note: Password are stored as BCrypt hashes. Plain password are never stored or logged.");

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        jLabel11.setText("Confirm Password :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel3))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtOutlets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 36, Short.MAX_VALUE)))))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnRefresh)
                    .addComponent(jLabel6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOutlets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateUser();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtOutletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutletsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtOutletsActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        searchData();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addUser();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteUser();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JComboBox<ComboItem> txtOutlets;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtRole;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JComboBox<String> txtStatus;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
